"""Load the data corpus, grade every device x claim cell, and emit outputs.

Outputs (written to ./build by default):
  - MATRIX.md     human-readable leaderboard with per-cell rationale
  - matrix.csv    machine-readable, one row per device x claim cell
  - heatmap.svg   color-coded grid for embedding in the README

Run:  python -m wearvalid build
"""
import csv
import os
from collections import defaultdict

import yaml

from .grade import grade_cell
from .normalize import normalize
from .heatmap import render_svg

GRADE_ORDER = ["A", "B", "C", "D", "F", "N"]
GRADE_LABEL = {
    "A": "Established valid",
    "B": "Conditionally valid / good but limited",
    "C": "Contested / insufficient",
    "D": "Unvalidated but marketed",
    "F": "Refuted",
    "N": "Not validatable (composite)",
}


def _load_yaml(path):
    with open(path, "r") as fh:
        return yaml.safe_load(fh)


def load_corpus(data_dir):
    swc = _load_yaml(os.path.join(data_dir, "swc.yaml"))
    claims = {c["id"]: c for c in _load_yaml(os.path.join(data_dir, "claims.yaml"))}
    devices = {d["id"]: d for d in _load_yaml(os.path.join(data_dir, "devices.yaml"))}

    studies = []
    sdir = os.path.join(data_dir, "studies")
    for fn in sorted(os.listdir(sdir)):
        if fn.endswith((".yaml", ".yml")):
            studies.append(_load_yaml(os.path.join(sdir, fn)))
    return swc, claims, devices, studies


def collect_measurements(claims, studies):
    """Group normalized measurements by (device, claim)."""
    cells = defaultdict(list)
    for st in studies:
        is_review = st.get("tier") in ("systematic_review", "umbrella_review")
        for m in st.get("measurements", []):
            claim = claims[m["claim"]]
            canon = normalize(m["reported"])
            cells[(m["device"], m["claim"])].append({
                "canon": canon,
                "independent": st.get("independent", True),
                "criterion": m.get("criterion", "unspecified"),
                "is_gold": m.get("criterion") in claim.get("gold_criteria", []),
                "is_review": is_review,
                "label": "%s (%s)" % (st["id"], m.get("condition", "n/a")),
                "study": st["id"],
            })
    return cells


def grade_all(swc, claims, devices, studies):
    cells = collect_measurements(claims, studies)

    # Universe of cells = every measured cell + every marketed cell.
    universe = set(cells.keys())
    for d in devices.values():
        for claim_id in d.get("markets", []):
            universe.add((d["id"], claim_id))

    verdicts = []
    for (device_id, claim_id) in sorted(universe):
        claim = claims[claim_id]
        swc_val = (swc.get(claim_id) or {}).get("swc")
        marketed = claim_id in devices.get(device_id, {}).get("markets", [])
        v = grade_cell(device_id, claim, cells.get((device_id, claim_id), []),
                       swc_val, marketed=marketed)
        verdicts.append(v)
    return verdicts


def coverage_stats(verdicts):
    counts = {g: 0 for g in GRADE_ORDER}
    for v in verdicts:
        counts[v.grade] += 1
    return counts


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def _grade_glyph(g):
    return {"A": "🟢 A", "B": "🟡 B", "C": "⚪ C", "D": "🟠 D", "F": "🔴 F", "N": "⚫ N"}[g]


def render_markdown(verdicts, claims, devices, counts):
    total = len(verdicts)
    lines = []
    lines.append("# Wearable Validity Matrix\n")
    lines.append("> Auto-generated by `python -m wearvalid build`. Every grade is "
                 "computed from study-level data in `data/` — do not edit by hand.\n")

    # Headline
    n_ab = counts["A"] + counts["B"]
    lines.append("## Headline\n")
    lines.append("- **%d** device×claim cells graded across **%d** devices.\n"
                 % (total, len({v.device for v in verdicts})))
    lines.append("- Grade A (established valid): **%d**. Grade B or better: **%d** (%.0f%%).\n"
                 % (counts["A"], n_ab, 100.0 * n_ab / total if total else 0))
    lines.append("- Unvalidated-but-marketed (**D**): %d · Refuted (**F**): %d · "
                 "Not-validatable composites (**N**): %d.\n"
                 % (counts["D"], counts["F"], counts["N"]))
    lines.append("")
    lines.append("![heatmap](heatmap.svg)\n")

    # Legend
    lines.append("## Grade legend\n")
    lines.append("| Grade | Meaning |")
    lines.append("|---|---|")
    for g in GRADE_ORDER:
        lines.append("| %s | %s |" % (_grade_glyph(g), GRADE_LABEL[g]))
    lines.append("")

    # Grid
    dev_ids = [d for d in devices]
    lines.append("## Matrix\n")
    header = "| Claim | " + " | ".join(devices[d]["label"] for d in dev_ids) + " |"
    sep = "|---|" + "|".join([":---:"] * len(dev_ids)) + "|"
    lines.append(header)
    lines.append(sep)
    by_cell = {(v.device, v.claim): v for v in verdicts}
    for claim_id, claim in claims.items():
        row = ["**%s**" % claim["label"]]
        for d in dev_ids:
            v = by_cell.get((d, claim_id))
            row.append(_grade_glyph(v.grade) if v else "·")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    # Per-cell detail (the auditable part)
    lines.append("## Audit trail (per-cell rationale)\n")
    lines.append("Every non-trivial verdict, with the evidence it was computed from.\n")
    graded = [v for v in verdicts if v.grade != "D"]
    for v in sorted(graded, key=lambda x: (GRADE_ORDER.index(x.grade), x.claim, x.device)):
        lines.append("### %s — %s · **Grade %s**\n" % (
            devices[v.device]["label"], claims[v.claim]["label"], v.grade))
        lines.append(v.rationale + "\n")
        if v.bias is not None or v.precision is not None or v.resolution_ratio is not None:
            bits = []
            if v.bias is not None:
                bits.append("bias=%.3g" % v.bias)
            if v.precision is not None:
                bits.append("precision(SD_diff)=%.3g" % v.precision)
            if v.resolution_ratio is not None:
                bits.append("Resolution Ratio R=%.2f" % v.resolution_ratio)
            lines.append("`" + ", ".join(bits) + "`\n")
        if v.bases:
            for b in v.bases:
                lines.append("- " + b)
            lines.append("")
    return "\n".join(lines) + "\n"


def write_csv(verdicts, path):
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["device", "claim", "grade", "n_studies", "n_goodquality",
                    "best_fidelity", "bias", "precision_sd", "resolution_ratio",
                    "rationale"])
        for v in verdicts:
            w.writerow([v.device, v.claim, v.grade, v.n_studies, v.n_goodquality,
                        v.best_fidelity, v.bias, v.precision, v.resolution_ratio,
                        v.rationale])


def build(data_dir, out_dir):
    swc, claims, devices, studies = load_corpus(data_dir)
    verdicts = grade_all(swc, claims, devices, studies)
    counts = coverage_stats(verdicts)

    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "MATRIX.md"), "w") as fh:
        fh.write(render_markdown(verdicts, claims, devices, counts))
    write_csv(verdicts, os.path.join(out_dir, "matrix.csv"))
    with open(os.path.join(out_dir, "heatmap.svg"), "w") as fh:
        fh.write(render_svg(verdicts, claims, devices))

    return verdicts, counts
